class VenezuelaData {
  static const Map<String, List<String>> citiesByState = {
    'Amazonas': [
      'Todos los destinos',
      'Puerto Ayacucho',
      'San Fernando de Atabapo',
      'San Carlos de Río Negro',
    ],
    'Anzoátegui': [
      'Todos los destinos',
      'Barcelona',
      'Puerto La Cruz',
      'Lechería',
      'Guanta',
      'El Tigre',
      'Anaco',
      'Cantaura',
    ],
    'Apure': [
      'Todos los destinos',
      'San Fernando de Apure',
      'Guasdualito',
      'Elorza',
      'Achaguas',
      'Biruaca',
    ],
    'Aragua': [
      'Todos los destinos',
      'Maracay',
      'Turmero',
      'La Victoria',
      'Cagua',
      'Palo Negro',
      'El Limón',
      'San Mateo',
    ],
    'Bolívar': [
      'Todos los destinos',
      'Ciudad Guayana (Puerto Ordaz/San Félix)',
      'Ciudad Bolívar',
      'Upata',
      'Caicara del Orinoco',
      'Tumeremo',
      'Guasipati',
      'El Callao',
      'Santa Elena de Uairén',
    ],
    'Carabobo': [
      'Todos los destinos',
      'Valencia',
      'Puerto Cabello',
      'Guacara',
      'Mariara',
      'San Joaquín',
      'Morón',
      'Bejuma',
      'Naguanagua',
      'San Diego',
    ],
    'Cojedes': [
      'Todos los destinos',
      'San Carlos',
      'Tinaco',
      'Tinaquillo',
      'El Pao',
    ],
    'Delta Amacuro': [
      'Todos los destinos',
      'Tucupita',
      'Curiapo',
      'Pedernales',
    ],
    'Distrito Capital': [
      'Todos los destinos',
      'Caracas (Centro)',
      'Caracas (Oeste)',
      'Caracas (Este)',
    ],
    'Falcón': [
      'Todos los destinos',
      'Coro',
      'Punto Fijo',
      'Dabajuro',
      'Churuguara',
      'Tucacas',
      'Chichiriviche',
    ],
    'Guárico': [
      'Todos los destinos',
      'San Juan de los Morros',
      'Calabozo',
      'Valle de la Pascua',
      'Zaraza',
      'Altagracia de Orituco',
    ],
    'Lara': [
      'Todos los destinos',
      'Barquisimeto',
      'Cabudare',
      'Carora',
      'El Tocuyo',
      'Quíbor',
      'Siquisique',
    ],
    'La Guaira': [
      'Todos los destinos',
      'La Guaira',
      'Maiquetía',
      'Catia La Mar',
      'Caraballeda',
      'Macuto',
      'Naiguatá',
    ],
    'Mérida': [
      'Todos los destinos',
      'Mérida (Centro)',
      'Ejido',
      'Tabay',
      'Mucuchíes',
      'Apartaderos',
      'Pico del Águila',
      'Timotes',
      'Santo Domingo',
      'Pueblo Llano',
      'Tovar',
      'El Vigía',
      'Bailadores',
      'Santa Cruz de Mora',
      'Lagunillas',
      'Nueva Bolivia',
    ],
    'Miranda': [
      'Todos los destinos',
      'Los Teques',
      'Guarenas',
      'Guatire',
      'Charallave',
      'Cúa',
      'Ocumare del Tuy',
      'Santa Teresa del Tuy',
      'San Antonio de los Altos',
      'Baruta',
      'Chacao',
      'Petare',
    ],
    'Monagas': [
      'Todos los destinos',
      'Maturín',
      'Punta de Mata',
      'Caripe',
      'Caripito',
    ],
    'Nueva Esparta': [
      'Todos los destinos',
      'Porlamar',
      'Pampatar',
      'La Asunción',
      'Juan Griego',
      'Punta de Piedras',
    ],
    'Portuguesa': [
      'Todos los destinos',
      'Guanare',
      'Acarigua',
      'Araure',
      'Turén',
      'Biscucuy',
      'Ospino',
    ],
    'Sucre': [
      'Todos los destinos',
      'Cumaná',
      'Carúpano',
      'Güiria',
      'Cariaco',
      'Marigüitar',
    ],
    'Táchira': [
      'Todos los destinos',
      'San Cristóbal',
      'Táriba',
      'Rubio',
      'San Antonio del Táchira',
      'Ureña',
      'La Grita',
      'El Cobre',
      'San Juan de Colón',
    ],
    'Trujillo': [
      'Todos los destinos',
      'Trujillo',
      'Valera',
      'Boconó',
      'Pampán',
      'Pampanito',
      'Escuque',
      'Betijoque',
      'Sabana de Mendoza',
    ],
    'Yaracuy': [
      'Todos los destinos',
      'San Felipe',
      'Yaritagua',
      'Chivacoa',
      'Nirgua',
    ],
    'Zulia': [
      'Todos los destinos',
      'Maracaibo',
      'San Francisco',
      'Cabimas',
      'Ciudad Ojeda',
      'Machiques',
      'La Villa del Rosario',
      'Santa Bárbara del Zulia',
      'El Venado',
    ],
  };
}
